cfg:
  cfg_current_filename: ''
  cfg_default: default_config_grid_manage_der.yaml
  cfg_user: user_config_grid_manage_der.yaml
  config_output_folder_name: /hkfs/home/haicore/iai/ii6824/Documents/PIDE/yaml/hpc/user_config_grid_manage_der_96_steps.yaml
cfg_settings:
  cfg_default_plot_path: /hkfs/home/haicore/iai/ii6824/Documents/PIDE/yaml/hpc/default_plot_config.yaml
  cfg_user_plot_path: /hkfs/home/haicore/iai/ii6824/Documents/PIDE/yaml/hpc/user_plot_config_grid.yaml
  helper_path: /hkfs/home/haicore/iai/ii6824/Documents/PIDE/helper
  input_data_path: /hkfs/home/haicore/iai/ii6824/PIDE/input_data
  input_data_type: .pickle
  output_data_path: /hkfs/home/haicore/iai/ii6824/Documents/PIDE/output/mcs_folder/96_steps_1-LV-rural1--0-sw_vde_base_datasource_rbc_pvbes_distributed_sc_ctrl_mpv_True_con_100
  output_data_type: ''
  output_file_type: .json
  output_test_path: /hkfs/home/haicore/iai/ii6824/PIDE/test
  run_main_base_path: /hkfs/home/haicore/iai/ii6824/Documents/PIDE
  sequence_id_path: /hkfs/home/haicore/iai/ii6824/Documents/PIDE/yaml/hpc/sequence_id.txt
  write_to_rawdata: false
  yaml_path: hpc
control_modes:
  pv_ctrl: datasource
  storage_p_ctrl: rbc_pvbes_distributed_sc_ctrl
  storage_q_ctrl: voltage_reactive_power_ctrl
  timeseries_ctrl: control_module
criticality:
  lines_max: 65.0
  transformer_max: 100.0
  v_crit_lower: 0.92
  v_crit_upper: 1.085
  v_delta_threshold: 0.01
  v_max: 1.1
  v_max_threshold: 1.035
  v_min: 0.9
  v_min_max_delta: 0.1
deltaTime: 15
maxTime: 180
mcs_settings:
  add_noise: true
  error_std_dev: 0.001
  flag_monte_carlo: true
  loc: 0.0
  num_monte_carlo_runs: 100
  seed_value: 1527
method: rbc
mpv_settings:
  mpv_benchmark: simbench
  mpv_concentration_rate_percent: 100.0
  mpv_flag: true
  mpv_inverter_apparent_power: 600
  mpv_inverter_apparent_power_watt: 800
  mpv_scaling: 0.6
  mpv_solar_cell_capacity: 800
  mpv_solar_cell_capacity_watt: 2000
rawdata:
  benchmark: simbench
  net_name: rural_grid_15
  sb_code: 1-LV-rural1--0-sw
  scaling:
    load: 1.0
    pv: 1.0
    storage: 1.0
  scenario: 2-future
  soc_initial: 0.0
  valid_sb_base_codes:
  - 1-LV-rural1--{}-sw
  - 1-LV-rural2--{}-sw
  - 1-LV-rural3--{}-sw
  - 1-LV-semiurb4--{}-sw
  - 1-LV-semiurb5--{}-sw
  - 1-LV-urban6--{}-sw
  valid_sb_code:
  - 1-LV-rural1--0-sw
  - 1-LV-rural2--0-sw
  - 1-LV-rural3--0-sw
  - 1-LV-semiurb4--0-sw
  - 1-LV-semiurb5--0-sw
  - 1-LV-urban6--0-sw
  - Customised
  valid_sb_scenario:
  - 0-today
  - 1-near future
  - 2-future
  valid_sb_scenario_storage:
  - 1-near future
  - 2-future
rbc:
  alpha: 0.5
  rendering_initialized: true
regulation_standard_modes:
- vde
- ieee
rlc:
  history: 1
sim:
  episode_limit: 96
  episode_start_day: 180
  episode_start_hour: 0
  episode_start_min_interval: 0
  max_iterations: 35135
  resolution: 15
  time_mode: selected
standard_modes:
- deadband
- base
- customised
vde:
  base:
    v_1: 0.93
    v_2: 1.0
    v_3: 1.0
    v_4: 1.0
    v_5: 1.07
    v_deadband_gain: 0.0
    v_high_gain: 0.0
    v_low_gain: 0.0
    v_nom: 1.0
    v_nom_net: 1.0
  customised:
    v_1: 0.93
    v_2: 1.0
    v_3: 1.0
    v_4: 1.0
    v_5: 1.07
    v_deadband_gain: 0.0
    v_high_gain: 0.0
    v_low_gain: 0.0
    v_nom: 1.0
    v_nom_net: 1.0
  deadband:
    v_1: 0.93
    v_2: 0.97
    v_3: 1.0
    v_4: 1.03
    v_5: 1.07
    v_deadband_gain: 0.06
    v_high_gain: 0.03
    v_low_gain: 0.03
    v_nom: 1.0
    v_nom_net: 1.0
  standard_mode: deadband
